### PR TITLE
fix(package.json): add types to exports

### LINKED ISSUE #189: ES Module Import Error
I'm getting the following error when importing `lib-r-math.js` into an ES module:

```
1. Could not find a declaration file for module 'lib-r-math.js'. 'node_modules/.pnpm/lib-r-math.js@2.0.0/node_modules/lib-r-math.js/dist/esm/index.mjs' implicitly has an 'any' type.
     There are types at 'node_modules/lib-r-math.js/dist/types/index.d.ts', but this result could not be resolved when respecting package.json "exports". The 'lib-r-math.js' library may need to update its package.json or typings. [7016]
```

### PR DESCRIPTION
**Pull request by b0o**
fixes #189

### CODE REVIEW

**Comment by jacobbogers** [comment]
Thank you for your contributions, could you give yourself attribution in CHANGELOG.md or shall i do it?

**Comment by jacobbogers** [comment]
Merged, thank you, I will make new release

**Comment by jacobbogers** [comment]
I added your contribution to the changelog will be releasing 2.0.1 shortly

**Comment by b0o** [comment]
Thank you! :tada:

**Pull request merged**
